# Generated by Django 5.2.7 on 2025-10-16 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('left_distance', models.FloatField(blank=True, null=True)),
                ('right_distance', models.FloatField(blank=True, null=True)),
                ('left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left_airport', to='airport.airport')),
                ('right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='right_airport', to='airport.airport')),
            ],
        ),
    ]
